# Generated by Django 4.2.30 on 2026-06-06 17:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='预约日期')),
                ('appointment_time', models.TimeField(verbose_name='预约时间')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '预约',
                'verbose_name_plural': '预约',
                'ordering': ['-appointment_date', '-appointment_time'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('female', '女'), ('male', '男'), ('other', '其他')], default='female', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='头像')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '顾客',
                'verbose_name_plural': '顾客',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NailDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='款式名称')),
                ('image', models.ImageField(upload_to='designs/', verbose_name='款式图片')),
                ('nail_shape', models.CharField(choices=[('oval', '椭圆形'), ('square', '方形'), ('squoval', '方圆形'), ('almond', '杏仁形'), ('stiletto', '尖形'), ('coffin', '棺材形'), ('ballerina', '芭蕾舞形'), ('round', '圆形')], max_length=20, verbose_name='甲型')),
                ('color_system', models.CharField(max_length=100, verbose_name='色系')),
                ('decoration', models.CharField(max_length=300, verbose_name='装饰元素')),
                ('occasion', models.CharField(choices=[('daily', '日常'), ('wedding', '婚礼'), ('party', '派对'), ('office', '职场'), ('festival', '节日'), ('travel', '旅行'), ('date', '约会')], max_length=20, verbose_name='适用场合')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='参考价格')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '美甲款式',
                'verbose_name_plural': '美甲款式',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StyleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='风格名称')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '风格标签',
                'verbose_name_plural': '风格标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='technicians/', verbose_name='头像')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='专长')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='入职日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '美甲师',
                'verbose_name_plural': '美甲师',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NailWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='works/', verbose_name='完成照片')),
                ('actual_nail_shape', models.CharField(blank=True, max_length=50, verbose_name='实际甲型')),
                ('actual_color', models.CharField(blank=True, max_length=100, verbose_name='实际色系')),
                ('duration_days', models.IntegerField(default=0, verbose_name='维持天数')),
                ('satisfaction', models.IntegerField(choices=[(1, '非常不满意'), (2, '不满意'), (3, '一般'), (4, '满意'), (5, '非常满意')], default=5, verbose_name='满意度')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='顾客反馈')),
                ('completed_at', models.DateField(default=datetime.date.today, verbose_name='完成日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='nail_app.appointment', verbose_name='关联预约')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='nail_app.customer', verbose_name='顾客')),
                ('design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nail_app.naildesign', verbose_name='参考款式')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='nail_app.technician', verbose_name='操作美甲师')),
            ],
            options={
                'verbose_name': '作品存档',
                'verbose_name_plural': '作品存档',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddField(
            model_name='naildesign',
            name='style_tags',
            field=models.ManyToManyField(blank=True, to='nail_app.styletag', verbose_name='风格标签'),
        ),
        migrations.AddField(
            model_name='naildesign',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designs', to='nail_app.technician', verbose_name='上传美甲师'),
        ),
        migrations.CreateModel(
            name='CustomerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_colors', models.CharField(blank=True, max_length=500, verbose_name='偏好色系')),
                ('preferred_shapes', models.CharField(blank=True, max_length=200, verbose_name='偏好甲型')),
                ('preferred_styles', models.CharField(blank=True, max_length=200, verbose_name='偏好风格')),
                ('preferred_occasions', models.CharField(blank=True, max_length=200, verbose_name='偏好场合')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='nail_app.customer', verbose_name='顾客')),
            ],
            options={
                'verbose_name': '顾客偏好',
                'verbose_name_plural': '顾客偏好',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='nail_app.customer', verbose_name='顾客'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='nail_app.naildesign', verbose_name='预约款式'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='nail_app.technician', verbose_name='美甲师'),
        ),
    ]
