# Generated by Django 4.2.30 on 2026-06-06 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nail_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nailwork',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='nail_app.appointment', verbose_name='关联预约'),
        ),
        migrations.AlterField(
            model_name='nailwork',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='works/', verbose_name='完成照片'),
        ),
    ]
