# Generated by Django 4.2.30 on 2026-06-07 01:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nail_app', '0002_alter_nailwork_appointment_alter_nailwork_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='churn_risk_score',
            field=models.FloatField(default=0, verbose_name='流失风险评分'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_contact_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近联系时间'),
        ),
        migrations.AddField(
            model_name='customer',
            name='member_level',
            field=models.CharField(choices=[('normal', '普通会员'), ('silver', '银卡会员'), ('gold', '金卡会员'), ('platinum', '钻石会员')], default='normal', max_length=20, verbose_name='会员等级'),
        ),
        migrations.AddField(
            model_name='customer',
            name='recommended_action',
            field=models.TextField(blank=True, verbose_name='推荐跟进动作'),
        ),
        migrations.CreateModel(
            name='RiskScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='风险评分')),
                ('factors', models.JSONField(default=dict, verbose_name='评分因子详情')),
                ('recorded_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='记录时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_histories', to='nail_app.customer', verbose_name='顾客')),
            ],
            options={
                'verbose_name': '风险评分历史',
                'verbose_name_plural': '风险评分历史',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', '电话'), ('wechat', '微信'), ('sms', '短信'), ('visit', '到店'), ('other', '其他')], default='wechat', max_length=20, verbose_name='联系方式')),
                ('content', models.TextField(verbose_name='联系内容')),
                ('contacted_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='联系时间')),
                ('operator', models.CharField(blank=True, max_length=50, verbose_name='操作人')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_records', to='nail_app.customer', verbose_name='顾客')),
            ],
            options={
                'verbose_name': '联系记录',
                'verbose_name_plural': '联系记录',
                'ordering': ['-contacted_at'],
            },
        ),
    ]
