# Generated by Django 4.2.30 on 2026-06-07 01:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nail_app', '0003_customer_churn_risk_score_customer_last_contact_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='try_on/', verbose_name='手部照片')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '识别中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('skin_tone', models.CharField(blank=True, choices=[('fair', '冷白肤色'), ('light', '白皙肤色'), ('medium', '自然肤色'), ('tan', '小麦肤色'), ('dark', '健康肤色')], max_length=20, verbose_name='识别肤色')),
                ('hand_shape', models.CharField(blank=True, choices=[('slender', '纤细修长型'), ('standard', '标准匀称型'), ('plump', '丰满圆润型'), ('broad', '宽厚有力型')], max_length=20, verbose_name='识别手型')),
                ('nail_length', models.CharField(blank=True, choices=[('very_short', '超短（<1mm）'), ('short', '短（1-3mm）'), ('medium', '中（3-6mm）'), ('long', '长（6-10mm）'), ('very_long', '超长（>10mm）')], max_length=20, verbose_name='识别指甲长度')),
                ('target_occasion', models.CharField(blank=True, choices=[('daily', '日常'), ('wedding', '婚礼'), ('party', '派对'), ('office', '职场'), ('festival', '节日'), ('travel', '旅行'), ('date', '约会')], max_length=20, verbose_name='目标场合')),
                ('budget', models.CharField(blank=True, choices=[('low', '平价（100元以下）'), ('medium', '中档（100-300元）'), ('high', '高档（300-600元）'), ('luxury', '奢华（600元以上）')], max_length=20, verbose_name='预算范围')),
                ('preferred_colors', models.CharField(blank=True, max_length=500, verbose_name='偏好色系（多选，逗号分隔）')),
                ('analysis_details', models.JSONField(default=dict, verbose_name='分析详情')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('converted_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_try_on', to='nail_app.appointment', verbose_name='转化预约')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='try_on_tasks', to='nail_app.customer', verbose_name='顾客')),
                ('reference_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referenced_by_try_ons', to='nail_app.nailwork', verbose_name='参考历史作品')),
            ],
            options={
                'verbose_name': '试甲任务',
                'verbose_name_plural': '试甲任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarDesignResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(default=0, verbose_name='相似度评分（0-100）')),
                ('shape_score', models.FloatField(default=0, verbose_name='甲型匹配分')),
                ('color_score', models.FloatField(default=0, verbose_name='色系匹配分')),
                ('decoration_score', models.FloatField(default=0, verbose_name='装饰匹配分')),
                ('style_score', models.FloatField(default=0, verbose_name='风格匹配分')),
                ('occasion_score', models.FloatField(default=0, verbose_name='场合匹配分')),
                ('satisfaction_score', models.FloatField(default=0, verbose_name='历史满意度分')),
                ('budget_score', models.FloatField(default=0, verbose_name='预算匹配分')),
                ('score_breakdown', models.JSONField(default=dict, verbose_name='评分分解')),
                ('rank', models.IntegerField(default=0, verbose_name='推荐排序')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='是否被浏览')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='浏览时间')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_matches', to='nail_app.naildesign', verbose_name='匹配款式')),
                ('try_on_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_results', to='nail_app.tryontask', verbose_name='试甲任务')),
            ],
            options={
                'verbose_name': '相似款式推荐结果',
                'verbose_name_plural': '相似款式推荐结果',
                'ordering': ['try_on_task', '-similarity_score'],
            },
        ),
        migrations.CreateModel(
            name='DesignClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_type', models.CharField(choices=[('view', '浏览'), ('compare', '对比'), ('favorite', '收藏'), ('book', '预约')], default='view', max_length=30, verbose_name='点击类型')),
                ('clicked_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='点击时间')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_clicks', to='nail_app.customer', verbose_name='点击顾客')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='nail_app.naildesign', verbose_name='被点击款式')),
                ('similar_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clicks', to='nail_app.similardesignresult', verbose_name='关联推荐结果')),
                ('try_on_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_logs', to='nail_app.tryontask', verbose_name='关联试甲任务')),
            ],
            options={
                'verbose_name': '款式点击日志',
                'verbose_name_plural': '款式点击日志',
                'ordering': ['-clicked_at'],
            },
        ),
    ]
